In [22]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html

import pandas as pd
import numpy as np

arrays = [['Falcon', 'Falcon', 'Parrot', 'Parrot'],
          ['Captive', 'Wild', 'Captive', 'Wild']]
arrays

[['Falcon', 'Falcon', 'Parrot', 'Parrot'],
 ['Captive', 'Wild', 'Captive', 'Wild']]

In [24]:
index = pd.MultiIndex.from_arrays(arrays, names=('Animal', 'Type'))
index

MultiIndex([('Falcon', 'Captive'),
            ('Falcon',    'Wild'),
            ('Parrot', 'Captive'),
            ('Parrot',    'Wild')],
           names=['Animal', 'Type'])

In [25]:
df = pd.DataFrame({'Max Speed': [390., 350., 30., 20.]}, index=index)
df

Max Speed
Animal Type              
Falcon Captive      390.0
       Wild         350.0
Parrot Captive       30.0
       Wild          20.0

In [26]:
l = [[1, 2, 3], [1, None, 4], [2, 1, 3], [1, 2, 2]]
df = pd.DataFrame(l, columns=["a", "b", "c"])
df

a    b  c
0  1  2.0  3
1  1  NaN  4
2  2  1.0  3
3  1  2.0  2

In [27]:
df.groupby(by=["b"]).sum()

a  c
b        
1.0  2  3
2.0  2  5

In [28]:
df.groupby(by=["b"])

In [2]:
import numpy as np
a = np.arange(12).reshape((3, 4))
a
# print(a[:, np.any(a < 2, axis = 0)])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
af = np.where((a < 6), True, False)
af

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [8]:
np.column_stack(np.where(af))

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [1, 0],
       [1, 1]], dtype=int64)

In [6]:
af = a.flatten()
af

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
print(f'rows: {np.any(a < 6, axis = 1)}')
print(f'cols: {np.any(a < 6, axis = 0)}')

rows: [ True  True False]
cols: [ True  True  True  True]
